FROM joyzoursky/python-chromedriver:3.9-selenium

WORKDIR /pysetup
COPY /app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /usr/src/app
RUN apt-get update
RUN apt-get -y install nodejs
RUN mkdir ./screenshots
RUN ln -sf /usr/share/zoneinfo/Asia/Yangon /etc/localtime


COPY start.sh /usr/src/app/start.sh
RUN chmod +x /usr/src/app/start.sh
CMD ["/usr/src/app/start.sh"]


#CMD nohup node ./proxy/proxy.js > ./proxy/log
#CMD ["/bin/bash", "-c", "nohup node ./proxy/proxy.js > ./proxy/log;ln -sf /usr/share/zoneinfo/Asia/Yangon /etc/localtime"]

COPY . /app/ /usr/src/app
